version: "3"
services:
  filter:
    build:
      context: ./image
      dockerfile: Dockerfile
    environment:
      MODULE_NAME: filter
      MODULE_TYPE: PROCESS
      EGRESS_URL: https://hookb.in/7ZZoWDREjNfa99D3yREY
      HANDLER_PORT: 80
      INPUT_LABEL: "temperature"
      OUTPUT_LABEL: "temp"
      OUTPUT_UNIT: "Celsius"
      CONDITION: "(>) greater than"
      COMPARE_VALUE: "20"
    ports:
      - 5000:80
