version: "3"
services:
  filter:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MODULE_NAME: filter
      EGRESS_API_HOST: https://hookb.in/7ZZoWDREjNfa99D3yREY
      HANDLER_PORT: 80
      INPUT_LABEL: "temperature"
      OUTPUT_LABEL: "temp"
      OUTPUT_UNIT: "Celsius"
      CONDITION: ">="
      COMPARE_VALUE: "20"
    ports:
      - 5000:80
