version: "3.0"
services:
  comparison-filter:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "comparison-filter"
      MODULE_TYPE: "Processing"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      EGRESS_URLS: "https://testdockercompose.free.beeceptor.com"
      INPUT_LABEL: "temperature"
      CONDITION: "(>) greater than"
      COMPARE_VALUE: 20
    ports:
      - 80:80
